version: "3.6"

services:
  client:
    build: ./client
    volumes:
      - "./client:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 3007:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=HKHKFSA
      - DB_DATABASE=obn_dev
      - DB_USER=obn_app
      - DB_PASSWORD=obn_app
      - DB_HOST=db
      - DB_PORT=5432
      - DATABASE=postgres
  db:
    image: postgis/postgis:12-3.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=obn_app
      - POSTGRES_PASSWORD=obn_app
      - POSTGRES_DB=obn_dev

volumes:
  postgres_data:
